version: '3'
services:
  jupyter:
    build: ./
   # image: jupyter/scipy-notebook
    ports:
      - "8000:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./results:/home/jovyan/results
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=123456
    command: start-notebook.sh